// Code generated by logcopter-gen; DO NOT EDIT.

package builtin

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.openai-app-server.pkg.harness.builtin")
